......F.F.
======================================================================
FAIL: test_can_save_a_POST_request_to_an_existing_list (lists.tests.NewListTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hadesshark/note-and-code/code/python/TDD/superlists/lists/tests.py", line 101, in test_can_save_a_POST_request_to_an_existing_list
    self.assertEqual(Item.objects.count(), 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_redirects_to_list_view (lists.tests.NewListTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hadesshark/note-and-code/code/python/TDD/superlists/lists/tests.py", line 114, in test_redirects_to_list_view
    self.assertRedirects(response, '/lists/%d/' % (correct_list.id,))
  File "/usr/local/lib/python3.5/site-packages/django/test/testcases.py", line 283, in assertRedirects
    (response.status_code, status_code))
AssertionError: 301 != 302 : Response didn't redirect as expected: Response code was 301 (expected 302)

----------------------------------------------------------------------
Ran 10 tests in 0.042s

FAILED (failures=2)
