...E....
======================================================================
ERROR: test_saing_and_retrieving_items (lists.tests.ListAndItemModelsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hadesshark/note-and-code/code/python/TDD/superlists/lists/tests.py", line 55, in test_saing_and_retrieving_items
    self.assertEqual(first_saved_item.list, list_)
AttributeError: 'Item' object has no attribute 'list'

----------------------------------------------------------------------
Ran 8 tests in 0.033s

FAILED (errors=1)
